import{a as L,S as b,i as v}from"./assets/vendor-b11e2a50.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const q="https://pixabay.com/api/",w="44774351-929c2aa0766411c652402d8c1";async function p(r,e=1,n=15){const s=`${q}?key=${w}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=${n}`,t=await L.get(s);if(!t.status===200)throw new Error(t.status);return t.data}let h;function g(r){const e=document.querySelector(".gallery"),n=r.map(s=>S(s)).join("");e.insertAdjacentHTML("beforeend",n),h?h.refresh():h=new b(".gallery a")}function S({webformatURL:r,largeImageURL:e,tags:n,likes:s,views:t,comments:o,downloads:a}){return`
  <div class="photo-card">
  <a href="${e}">
    <img cass="img" src="${r}" alt="${n}" loading="lazy"/>
    </a>
      <div class="info">
        <p class="info-item"><b>Likes </b>${s}</p>
        <p  class="info-item"><b>Views </b>${t}</p>
        <p class="info-item"><b>Comments </b>${o}</p>
        <p class="info-item"><b>Downloads </b>${a}</p>
      </div>
</div>`}function c(r,e="info"){v[e]({title:"",message:r,position:"topRight"})}function $(){document.querySelector(".gallery").innerHTML=""}function y(){document.querySelector(".loader").classList.remove("hidden")}function d(){document.querySelector(".loader").classList.add("hidden")}function E(){const e=document.querySelector(".gallery").querySelector(".photo-card");return e?e.getBoundingClientRect().height:0}const P=document.querySelector(".search-form"),m=document.querySelector("#search-input"),i=document.querySelector(".btn-load-more");let l="",u=1;const f=15;P.addEventListener("submit",async r=>{if(r.preventDefault(),l=m.value.trim(),!l){c("Please enter a search query.","warning");return}u=1,$(),y(),m.value="";try{const e=await p(l,u,f);if(d(),e.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!","error"),i.classList.add("hidden");return}g(e.hits),e.hits.length===f?i.classList.remove("hidden"):i.classList.add("hidden")}catch(e){d(),c("Error: "+e.message)}});i.addEventListener("click",async()=>{u+=1,y();try{const r=await p(l,u,f);d(),g(r.hits),r.hits.length<f&&(i.classList.add("hidden"),c("We're sorry, but you've reached the of search results.","info"));const e=E();window.scrollBy({top:e*2,behavior:"smooth"})}catch(r){d(),c("Error:"+r.message),i.classList.add("hidden")}});
//# sourceMappingURL=commonHelpers.js.map
